fix: adds version 3.0.4 to supported versions
swagger-api/swagger-ui pull request #10247
Opened 2024-12-27 16:05 UTC by baywet

### Description

adds version 3.0.4 to the list of supported versions

3.0.4 is a maintenance release of the specification that does not change any of the functional aspects.
https://www.openapis.org/blog/2024/10/25/announcing-openapi-specification-patch-releases

### Motivation and Context

fixes https://github.com/microsoft/OpenAPI.NET/issues/2030

### How Has This Been Tested?

This has NOT been tested beyond the affected unit tests. However the changes are straightforward and minor, I do not expect any side effects.
I'd appreciate if anyone could take the time to pull and test this just for sanity.

### Screenshots (if appropriate):

## Checklist

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [x] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

2025-01-01 15:29 UTC, cydhhp approved these changes
merge them

2025-01-07 19:12 UTC, baywet commented
@char0n since we've worked together on the spec and since you've contributed a lot on this project, I thought maybe you could help get this merged?

2025-01-10 14:36 UTC, MarijnPessers commented
Would be nice to get this fixed quickly.

2025-01-17 16:03 UTC, kciliento-genetec commented
Any news ?

2025-01-29 15:12 UTC, twurm commented
Any word on what the hold up is?

2025-01-29 15:26 UTC, richard-collette-precisely commented
@baywet - Maybe merge base branch in so this can continue to progress?

2025-01-29 15:59 UTC, baywet commented
@richard-collette-precisely done! Let me know if anything else is needed to get this merged

2025-01-29 17:19 UTC, richard-collette-precisely commented
@baywet - We need a reviewer.  Unfortunately I am not one of them.  Thank you for the PR though.

2025-02-04 05:57 UTC, cydhhp approved these changes
approve

2025-02-04 06:03 UTC, cydhhp commented
I am confused, already reviewed, why not merge?

2025-02-04 07:38 UTC, smutlubay approved these changes

2025-02-04 14:15 UTC, alec-petersen commented
@char0n would we be able to get a review from you on this? Not sure who all the maintainers are.

2025-02-11 21:43 UTC, jeremyfiel commented
This will continue to be a problem for each new release. They are currently working on 3.2 minor release and they are also considering to move to major.minor only, without the patch release. The entire `openapi` version validation function should be refactored to account for those upcoming changes. 

discussion about major.minor: https://github.com/OAI/OpenAPI-Specification/discussions/4233

3.2 release WIP: https://github.com/OAI/OpenAPI-Specification/milestone/12

3.1.2 release WIP: https://github.com/OAI/OpenAPI-Specification/milestone/17

2025-02-11 21:52 UTC, richard-collette-precisely commented
> This will continue to be a problem for each new release. They are currently working on 3.2 minor release and they are also considering to move to major.minor only, without the patch release. The entire `openapi` version validation function should be refactored to account for those upcoming changes.
> 
> discussion about major.minor: [OAI/OpenAPI-Specification#4233](https://github.com/OAI/OpenAPI-Specification/discussions/4233)
> 
> 3.2 release WIP: https://github.com/OAI/OpenAPI-Specification/milestone/12
> 
> 3.1.2 release WIP: https://github.com/OAI/OpenAPI-Specification/milestone/17

But at this time, those things do not exist and the UI cannot purport to support something that it may not, so the idea of refactoring belongs to another issue, not this one.  This one addresses the ground truth, today.

6.5 weeks and this hasn't been merged, is mind blowing.  This PR is on the verge of just being a documentation update.

2025-02-12 05:12 UTC, ibakirov commented
Still waiting...

2025-02-13 14:13 UTC, ZeynelKoca approved these changes

2025-02-13 14:20 UTC, ZeynelKoca commented
My team and I are quite dependent on this PR being merged. What's the hold-up?

2025-02-13 14:28 UTC, alec-petersen commented
Help @char0n, you're our only hope

![image](https://github.com/user-attachments/assets/f4c543ac-b24d-4a21-bfd7-b51929532c58)

2025-02-13 15:03 UTC, smutlubay commented
@alec-petersen I even sent an email to @char0n but he didn't care :D

2025-02-13 15:13 UTC, alec-petersen commented
@frantuma @ponelat @MiloszTarka Would we be able to get an approval for this PR? Thank you!

2025-02-14 12:50 UTC, baywet commented
@bve-wd while I agree with you in principle, my goal here was to make the least amount of changes possible to get reviewed and merged by maintainers as fast as possible...

2025-02-14 14:29 UTC, richard-collette-precisely commented
> @bve-wd while I agree with you in principle, my goal here was to make the least amount of changes possible to get reviewed and merged by maintainers as fast as possible...

Agreed, a separate issue with additional debate can cover change in behavior.

2025-02-17 14:47 UTC, char0n commented
Hi everybody,

Let's **move things forward**. Sorry for delay in communication. 

> @char0n since we've worked together on the spec and since you've contributed a lot on this project, I thought maybe you could help get this merged?

@baywet, that's my mission now.

> @alec-petersen I even sent an email to @char0n but he didn't care :D

I've seen your email and I do care deeply.

2025-02-17 14:58 UTC, char0n commented on README.md
> +| Swagger UI Version | Release Date | OpenAPI Spec compatibility                           | Notes                                                                 |
Can you please following table?

```md
| Swagger UI Version | Release Date | OpenAPI Spec Compatibility                           | Notes                                                                  |
|--------------------|--------------|------------------------------------------------------|------------------------------------------------------------------------|
| 5.19.0             | 2025-02-17   | 2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1 | [tag v5.19.0](https://github.com/swagger-api/swagger-ui/tree/v5.33.0)  |
| 5.0.0              | 2023-06-12   | 2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0               | [tag v5.0.0](https://github.com/swagger-api/swagger-ui/tree/v5.0.0)    |
| 4.0.0              | 2021-11-03   | 2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3                      | [tag v4.0.0](https://github.com/swagger-api/swagger-ui/tree/v4.0.0)    |
| 3.18.3             | 2018-08-03   | 2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3                      | [tag v3.18.3](https://github.com/swagger-api/swagger-ui/tree/v3.18.3)  |
| 3.0.21             | 2017-07-26   | 2.0                                                  | [tag v3.0.21](https://github.com/swagger-api/swagger-ui/tree/v3.0.21)  |
| 2.2.10             | 2017-01-04   | 1.1, 1.2, 2.0                                        | [tag v2.2.10](https://github.com/swagger-api/swagger-ui/tree/v2.2.10)  |
| 2.1.5              | 2016-07-20   | 1.1, 1.2, 2.0                                        | [tag v2.1.5](https://github.com/swagger-api/swagger-ui/tree/v2.1.5)    |
| 2.0.24             | 2014-09-12   | 1.1, 1.2                                             | [tag v2.0.24](https://github.com/swagger-api/swagger-ui/tree/v2.0.24)  |
| 1.0.13             | 2013-03-08   | 1.1, 1.2                                             | [tag v1.0.13](https://github.com/swagger-api/swagger-ui/tree/v1.0.13)  |
| 1.0.1              | 2011-10-11   | 1.0, 1.1                                             | [tag v1.0.1](https://github.com/swagger-api/swagger-ui/tree/v1.0.1)    |
```

2025-02-17 15:01 UTC, char0n commented on src/core/plugins/oas3/helpers.jsx
> +    /^3\.0\.([01234])(?:-rc[012])?$/.test(oasVersion)
We need to have this aligned with how [ApiDOM hadles version matching](https://github.com/swagger-api/apidom/blob/main/packages/apidom-parser-adapter-openapi-json-3-0/src/adapter.ts#L12)

We now need to be forward compatible with only supporting sensible future versions.

```suggestion
    typeof oasVersion === "string" && /^3\.0\.(?:[1-9]\d*|0)$/.test(oasVersion)
```

2025-02-17 15:03 UTC, char0n requested changes
Two changes need and we're looking good for a merge.

2025-02-17 15:05 UTC, baywet commented on README.md
> +| Swagger UI Version | Release Date | OpenAPI Spec compatibility                           | Notes                                                                 |
done, I took the liberty to align the tag version in the link to 19 as well

2025-02-17 15:07 UTC, char0n commented on README.md
> +| Swagger UI Version | Release Date | OpenAPI Spec compatibility                           | Notes                                                                 |
THanks! I did a mistake in the link number ;]

2025-02-17 15:07 UTC, baywet commented
@char0n thanks for the review, just pushed the changes. Let me know what you think.

2025-02-17 15:09 UTC, baywet commented on src/core/plugins/oas3/helpers.jsx
> +    typeof oasVersion === "string" && /^3\.0\.(?:[1-9]\d*|0)$/.test(oasVersion)
```suggestion
    /^3\.0\.(?:[1-9]\d*|0)$/.test(oasVersion)
```

2025-02-17 15:24 UTC, char0n commented
@baywet thanks for the contribution!

2025-02-17 15:30 UTC, char0n commented
@bve-wd yes you are right.

From historical perspective, OpenAPI editors have stipulated that 3.0.3 was the last version of 3.0 line. Now we have 3.0.4 and they say again 3.0.4 is the last one. We already did changes to other Swagger JavaScript projects to be forward compatible, please see https://github.com/swagger-api/swagger-ui/pull/10247#discussion_r1958382662. I've requested change in this PR to be aligned with this. OpenAPI 3.1 matching is already forward compatible for some time: https://github.com/swagger-api/swagger-ui/blob/df9aadf9712a8416bfa9d66f4b3c846e6fc0895f/src/core/plugins/oas31/fn.js#L10

2025-02-17 15:33 UTC, merged

2025-02-17 15:33 UTC, char0n commented
Release ETA - imminent. I'll need to follow up with some additional changes.

2025-02-17 16:24 UTC, frankkilcommins commented
Thanks @char0n ❤️

2025-02-17 16:36 UTC, char0n commented
NOTE: It was technically possible to resolve this issue with a simple plugin:

```js
const OpenAPI304Plugin = () => {
  return {
    statePlugins: {
      spec: {
        selectors: {
          isOAS30: (jsSpec) => {
            const oasVersion = jsSpec.get('json').get("openapi")
            return typeof oasVersion === "string" && /^3\.0\.(?:[1-9]\d*|0)$/.test(oasVersion)
          }
        }
      }
    }
  }
}

const ui = SwaggerUIBundle({
  url: "https://petstore.swagger.io/v2/swagger.json",
  dom_id: "#swagger-ui",
  presets: [
    SwaggerUIBundle.presets.apis,
    SwaggerUIStandalonePreset
  ],
  plugins: [
    SwaggerUIBundle.plugins.DownloadUrl,
    OpenAPI304Plugin,
  ],
  // requestSnippetsEnabled: true,
  layout: "StandaloneLayout"
})
```

2025-02-17 16:44 UTC, char0n commented
The change has been released as https://github.com/swagger-api/swagger-ui/releases/tag/v5.19.0

2025-03-13 16:20 UTC, GearTheWorld commented
Wow, I just loaded a project that was working just fine last week and no code has changed in that project but VS 2022 was updated from 17.3.2 to 17.3.3 and boom, "Unable to render this definition..." error

            app.UseSwagger(c =>
            {
                c.SerializeAsV2 = true;
            });

This solved the issue.  I honestly don't know why
Previously I didn't have V2 there.