Response examples should respect media-type
swagger-api/swagger-ui pull request #6456
Opened 2020-10-02 14:27 UTC by mathis-m

### Description

Response examples do not respect the media type selected.
It just stringifies the json representation of the sample provided via `examples` or `example` keyword.
It should use the `getSampleSchema` method, which does take care of the content-type // media-type.

### Motivation and Context

Fixes #6442 

### How Has This Been Tested?

- in browser
- via new tests for the bug

## Checklist

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [x] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [x] All new and existing tests passed.

2020-10-02 21:27 UTC, tim-lai commented
@mathis-m looks like linting errors that fail CI

2020-10-02 21:29 UTC, mathis-m commented
@tim-lai gonna fix that in some hours

2020-10-04 22:13 UTC, mathis-m commented
My approach is to override the response schema's example in case there is a matching media type example defined.
And use the new schema with the getSampleSchema util to generate a matching example.

2020-10-05 00:42 UTC, Rmkasun approved these changes

2020-10-07 23:39 UTC, tim-lai requested changes

2020-10-07 23:39 UTC, tim-lai commented on src/core/components/response.jsx
> +      oldSchema.example = typeof newExample.toJS === "function"
let's use `isFunc` from `core/utils` here.

2020-10-07 23:41 UTC, tim-lai commented
still failing CI. this time in `bugs/5458.js`

2020-10-08 06:43 UTC, mathis-m commented on src/core/components/response.jsx
> +      oldSchema.example = typeof newExample.toJS === "function"
fixed with 3db8f62

2020-10-08 06:44 UTC, mathis-m commented
> still failing CI. this time in `bugs/5458.js`

fixed.

2020-10-08 11:40 UTC, mathis-m commented
> My approach is to override the response schema's example in case there is a matching media type example defined.
> And use the new schema with the getSampleSchema util to generate a matching example.

In case of xml this will not work as described in #6470

2020-10-16 17:55 UTC, tim-lai approved these changes

2020-10-16 20:52 UTC, merged