Added support for showExtensions on Response objects
swagger-api/swagger-ui pull request #6535
Opened 2020-10-19 23:25 UTC by shelbys

If you appreciate this contribution, please add a `hacktoberfest-accepted` Label to the PR, so it'll be tracked

### Description
Add same ability to show `x-` extensions for Response objects, just like already supported for Operations, Parameters, and Schemas

### Motivation and Context
We actively use `x-` extensions on Response objects to better detail individual cases, but they're currently not shown in `swagger-ui

### How Has This Been Tested?
I manually verified locally with changes to PetStore, but didn't find any automated tests to extend.  Let me know if I missed anything

## Checklist

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [X] Improvements (misc. changes to existing features)
- [X] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [X] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [X] My changes require a change to the project documentation.
- [X] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [X] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

2020-10-20 22:24 UTC, tim-lai commented
@shelbys Thanks for the PR! Functionally looks good. However, it should come with new tests 1) where using `x-` extension does in fact render, and 2) where not using `x-` extension does not render the Response Extension component.

2020-10-20 22:26 UTC, tim-lai requested changes

2020-10-20 22:26 UTC, tim-lai commented on src/core/components/response-extension.jsx
> +export const ResponseExt = ({ xKey, xVal }) => {
let's use a fully descriptive name, such as `ResponseExtension`

2020-10-20 22:59 UTC, shelbys commented
@tim-lai - I'm happy to add some tests, just didn't find any to model off.  Do you have a pointer to a test I can use as a starting point?

2020-10-21 03:37 UTC, shelbys commented
@tim-lai - Renamed to ResponseExtension, and tests added

2020-10-22 00:58 UTC, tim-lai approved these changes

2020-10-22 01:49 UTC, merged

2020-10-22 01:49 UTC, tim-lai commented
@shelbys Merged! Thanks for the contribution!