feat: add tryItOutEnabled configuration
swagger-api/swagger-ui pull request #6865
Opened 2021-01-24 23:14 UTC by kyle-apex

allow users to set tryItOutEnabled: true to display
the "Try it out" section by default

### Motivation and Context
Addressed #2805 

### How Has This Been Tested?
Ran in browser by setting ?tryItOutEnabled=true
Added Cypress test.

## Checklist

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [X] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [X] are not breaking changes.

### Documentation
- [ ] My changes do not require a change to the project documentation.
- [X] My changes require a change to the project documentation.
- [X] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [X] My changes can and should be tested by unit and/or integration tests.
- [X] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [X] All new and existing tests passed.

2021-01-25 04:45 UTC, mathis-m commented
Fixes #6528

2021-01-25 18:56 UTC, tim-lai requested changes
@kyle-apex Thanks for the PR! Functionally looks good, but let's add a "negative" test, where `?tryItOutEnabled=false` still renders properly and doesn't display an expanded view.

2021-01-25 20:13 UTC, kyle-apex commented
@tim-lai Thanks for the tip.  As it turns out, setting tryItOutEnabled=false behaved as if it was true.  I fixed the issue for this configuration; however, it's worth mentioning as a future to-do that the previously existing boolean parameter configurations (ex: displayRequestDuration, displayOperationId) would fail the ?parameter=false test.

2021-01-25 23:02 UTC, tim-lai commented on src/core/containers/OperationContainer.jsx
> +      tryItOutEnabled: tryItOutEnabled && tryItOutEnabled !== "false",
```suggestion
      tryItOutEnabled: tryItOutEnabled && tryItOutEnabled === "true",
```

2021-01-25 23:04 UTC, tim-lai commented
@kyle-apex Thanks, good to know about other cases for future PR(s). I made a commit suggestion, to explicitly check for "true".

2021-01-26 16:59 UTC, tim-lai approved these changes

2021-01-26 17:00 UTC, merged

2021-01-26 17:00 UTC, tim-lai commented
@kyle-apex PR merged! Thanks for the contribution!

2021-01-26 17:02 UTC, kyle-apex commented
@tim-lai Thanks for your help and patience on my first submission!

2021-02-03 15:28 UTC, OndraZizka commented
Hi, when is this going to be released? And will it be controlled only in URL? Or can it be propagated from Spring config YAML, I guess through OpenAPI?

2021-02-03 17:43 UTC, mathis-m commented
@OndraZizka I think it can be configured via all available config options.

2021-02-11 13:41 UTC, jonatan-bengtsson commented
Hi, I'm using the latest `openapi-ui` in a Spring project. 
Could someone help me figure out how to enable this flag?
It doesn't seem to be a available flag via `springdoc` config in `application.yaml` (yet anyways).
Is there a way to still enable `swagger-ui` config flags?