Decode model schema name on model component
swagger-api/swagger-ui pull request #8400
Opened 2023-02-21 13:22 UTC by souenzzo

### Description
Decodes the schema name on model 

### Motivation and Context
Partially fixes #5626 (only fixes for OpenAPI v3)

### How Has This Been Tested?
- Go to `localhost:3200`
- Paste this data-url in  the url field

```
data:application/json;base64,eyJjb21wb25lbnRzIjp7InNjaGVtYXMiOnsiYVwvYitjIjp7InR5cGUiOiJudW1iZXIifX19LCJvcGVuYXBpIjoiMy4wLjMiLCJwYXRocyI6eyJcLyI6eyJnZXQiOnsicmVzcG9uc2VzIjp7ImRlZmF1bHQiOnsiY29udGVudCI6eyJhcHBsaWNhdGlvblwvanNvbiI6eyJzY2hlbWEiOnsiJHJlZiI6IiNcL2NvbXBvbmVudHNcL3NjaGVtYXNcL2F+MWIlMkJjIn19fX19fX19fQ==
```

- Expand `/` route
- Switch the default response from `example value` to `model`
- You should see `a/b+c`, without any `~1` or `%B2`

### Screenshots (if appropriate):
<img width="338" alt="Screenshot 2023-02-21 at 10 15 54" src="https://user-images.githubusercontent.com/3241703/220354904-80c2be39-6436-41ac-b77d-bf10c24e9a1c.png">
Before screenshot in  #5626

### My PR contains... 
- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [x] Bug fixes (non-breaking change which fixes an issue)
- [ ] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [x] are not breaking changes.

### Documentation
- [x] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [ ] My changes can not or do not need to be tested.
- [x] My changes can and should be tested by unit and/or integration tests.
- [x] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

❗ *help section* ❗
- I'm almost sure that my test will not run (i think that these is something wrong with the import)
- I believe that this function may be moved to an `utils` namespace or something like it
- Let's add more test cases ;)
- Let's fix for Swagger V2 too

2023-03-08 12:45 UTC, souenzzo commented
@ponelat

2023-03-10 11:40 UTC, ponelat commented
Thanks for the fix @souenzzo.
When you say the test won't run... does it run? I don't understand. 
Happy to get this merged, as the model name is mostly visual. Not sure about all the edge-cases of JSON Pointer and URL encoding. 

@souenzzo could you update the branch. 
@char0n any reason the PR builders aren't running, is it to do with the Draft Status of this PR?

2023-03-11 10:09 UTC, char0n requested changes
Please have a look at my code review comments.

2023-03-11 10:09 UTC, char0n commented on src/core/components/model.jsx
> +export let decodeRefName = s => decodeURIComponent(s.replace(/~1/, "/").replace(/~0/, "~"))
Again, thanks for contributing!

**1.** [decodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent) can throw [URIError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError) in certain cases like for example: `c%d`. JSON Pointer specification unfortunately allow to use encoded strings like  `c%d`, which means we have to compensate for that cornser-case. More info in [RFC6901, section 5](https://www.rfc-editor.org/rfc/rfc6901#section-5).

**2.** The regex pattern you used only replaces first occurrence of encoded JSON Pointer symbols and ignore the rest.

Here is a suggestion for you function that addressed both the issues mentioned above:

```suggestion
export let decodeRefName = uri => {
  const unescaped = uri.replace(/~1/g, "/").replace(/~0/g, "~")
  
  try {
    return decodeURIComponent(unescaped)
  } catch {
    return unescaped
  }
}
```

PS: can I you pleas also provide more tests coverage for the cases that my suggestion tries to fix? Thanks!

2023-03-13 08:07 UTC, souenzzo commented
@char0n done

2023-03-13 10:07 UTC, char0n approved these changes
LGTM

2023-03-13 10:10 UTC, char0n commented on src/core/components/model.jsx
> +let decodeRefName = uri => {
```suggestion
const decodeRefName = uri => {
```

2023-03-13 10:11 UTC, char0n commented on src/core/components/model.jsx
> +let decodeRefName = uri => {
We broke away from the `let` some time ago, and we use now industry strandard practices and use `const` whenever possible.

2023-03-13 10:55 UTC, char0n commented
Did some final style changes before the merge.

2023-03-13 10:59 UTC, merged

2023-03-15 17:59 UTC, souenzzo commented
@char0n tnks :) 

Btw, a feedback from the contribution process:

would be nice if the linter warn us about const vs let usage.

2023-03-16 07:25 UTC, char0n commented
Hi @souenzzo,

> would be nice if the linter warn us about const vs let usage.

Yes, automated linting is the plan. Utilizing prettier + eslint + aribnb codestyle will be utilized (as it's already has been done for SwaggerEditor and SwaggerClient). That would require to convert entire codebase. Meanwhile we have to check that manually unfortunately which decrease dev experience. Thanks for the feedback!